apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w8yxttfpk-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6bb554041f.ymto.p3.openshiftapps.com/rhtap/rhtap-qe:a7bbcc7f22f07c079bc10053725fefe65ea15d25@sha256:20c9a5a1c7e1ff0661643bb9ea7aed4c78ac5c0590df90a1ac99911a3a9235fb
          name: container-image
