apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w8yxttfpk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w8yxttfpk-java-quarkus-gitops